@startuml Manage Hospital (GET_ONE)

header Sample VacQ Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Hospital (GET_ONE)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:hospitals" as routerHospitals
participant "<<controllers>>\n:hospitals" as controllersHospitals
participant "<<model>>\n:Hospital" as modelHospital
database "<<MongoDB>>\n:hospitals" as HospitalsDatabase

client->server ++:req.get('/hospitals/:id')
server->routerHospitals ++:app.use('/hospitals/:id',hospitals)
routerHospitals -> controllersHospitals ++:getHospital(req)
controllersHospitals->modelHospital ++:findById(req.params.id)
modelHospital ->HospitalsDatabase ++: Query for hospital by ID
HospitalsDatabase --> modelHospital --: hospital data
controllersHospitals <-- modelHospital --:hospital data
controllersHospitals->client --:response with hospital data
@enduml 
