@startuml Manage Hospital (GET ONE)

header Manage Hospital Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Hospital (GET ONE)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:hospitals" as routerHospitals
participant "<<controllers>>\n:hospitals" as controllersHospitals
participant "<<model>>\n:Hospital" as modelHospital
database "<<MongoDB>>\n:hospitals" as HospitalsDatabase

client->server ++:req.get('/hospitals/{id}')
server->routerHospitals ++:app.use('/hospitals/{id}',hospitals)
routerHospitals -> controllersHospitals ++:getHospital(id)
controllersHospitals->modelHospital ++:get(req.body)
modelHospital ->HospitalsDatabase ++: HospitalSchema
HospitalsDatabase --> modelHospital --: hospital
controllersHospitals <-- modelHospital --:hospital
controllersHospitals->client --:response, hospitals

@enduml
